# HW Chapter 4
## by Ledin Menjivar


```{r}
stevens = matrix(c(1,1,13,14,1,1,11,15,1,2,23,27,1,2,25,29,1,3,32,31,1,3,35,37,2,1,45,47,
                   2,1,55,58,2,1,65,63,2,2,75,78,2,2,65,66,2,2,87,85,3,1,88,85,3,1,91,93,
                   3,1,24,25,3,1,65,68,3,2,43,41,3,2,54,53,3,2,65,68,3,2,76,74),
                 ncol = 4, byrow = TRUE)
colnames(stevens) = paste("V",1:4,sep = "")
rownames(stevens) = paste("S",1:20,sep="")
stevens
```


**MANOVA One Way Design**

```{r}
#install.packages("MASS")
#install.packages("car")
#install.packages("psych")
library(MASS)
library(car)
library(psych)
```
```{r}
grp = factor(stevens[,1])
Y = (stevens[,3:4])
fit = manova(Y~grp)
summary(fit,test="Wilks")
summary(fit,test="Pillai")
summary(fit,test = "Hotelling-Lawley")
summary(fit,test = "Roy")
summary.aov(fit)
```

```{r}
anovadata = data.frame(stevens)
names(anovadata) = c("method","class","ach1","ach2")
anovadata
describeBy(anovadata,anovadata$method)
```

**MANOVA Factorial Design**
```{r}
stevens = matrix(c(1,1,13,14,1,1,11,15,1,2,23,27,1,2,25,29,1,3,32,31,1,3,35,37,2,1,45,47,
                   2,1,55,58,2,1,65,63,2,2,75,78,2,2,65,66,2,2,87,85,3,1,88,85,3,1,91,93,
                   3,1,24,25,3,1,65,68,3,2,43,41,3,2,54,53,3,2,65,68,3,2,76,74),
                 ncol = 4, byrow = TRUE)
stevens = data.frame(stevens)
names(stevens) = c("method","class","ach1","ach2")
stevens
```

```{r}
# Factorial MANOVA: 3 methods and 2 classes
fit = manova(cbind(ach1,ach2)~method + class +method*class,data=stevens)
summary(fit,test="Wilks")
summary(fit,test="Pillai")
summary(fit,test = "Hotelling-Lawley")
summary(fit,test = "Roy")
```

```{r}
#Two different variable ordering for Type I SS
fit.model1 = manova(cbind(ach1,ach2)~method + class +method*class,data=stevens)
summary(fit.model1,test="Wilks")

fit.model2 = manova(cbind(ach1,ach2)~class + method +method*class,data=stevens)
summary(fit.model2,test="Wilks")

fit.model1 = manova(cbind(ach1,ach2)~method + class +method*class,data=stevens)
summary(fit.model1,test="Wilks")

fit.model2 = manova(cbind(ach1,ach2)~class+method +method*class,data=stevens)
summary(fit.model2,test="Wilks")

anova(fit.model1,fit.model2)
```

```{r}
library(car)
out = lm(cbind(ach1,ach2)~method+class+method*class-1,data=stevens)
Manova(out,multivariate=TRUE,type=c("II"),test="Wilks")
Manova(out,multivariate=TRUE,type=c("III"),test="Wilks")
```

```{r}
library(psych)
anovadata = data.frame(stevens)
names(anovadata) = c("method","class","ach1","ach2")
anovadata
describeBy(anovadata,anovadata$method)
describeBy(anovadata,anovadata$class)

```


